cookie:
  expiry_days: 1
  key: pwcm
  name: nakheel_cookie
credentials:
  usernames:
    caroline:
      email: caroline.sibai@artefact.com
      name: Caroline Sibai
      password: $2b$12$JhVUhWU9LtfQBSo7Ifr84edh1.glts3amS8r1e/N0rLAnLNlnERWq   
    roland:
      email: roland.debbane@artefact.com
      name: Roland Debbane
      password: $2b$12$JhVUhWU9LtfQBSo7Ifr84edh1.glts3amS8r1e/N0rLAnLNlnERWq
    yedhu:
      email: yedhu.krishna@artefact.com
      name: Yedhu Krishna
      password: $2b$12$JhVUhWU9LtfQBSo7Ifr84edh1.glts3amS8r1e/N0rLAnLNlnERWq
preauthorized:
  emails:
  - me@mail.com